<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <groupId>tech.smartboot.feat</groupId>
    <version>2.2.0</version>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>benchmark</artifactId>
    <properties>
        <feat.version>2.2.0</feat.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>tech.smartboot.feat</groupId>
            <artifactId>feat-cloud-starter</artifactId>
            <version>${feat.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <version>4.1.0</version>
        </dependency>
        <dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-core</artifactId>
            <version>5.1.4</version>
        </dependency>
        <dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-web</artifactId>
            <version>5.1.4</version>
        </dependency>
    </dependencies>
</project>