CREATE TABLE IF NOT EXISTS sys_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    display_name VARCHAR(64) NOT NULL,
    role_code VARCHAR(32) NOT NULL,
    status SMALLINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

MERGE INTO sys_user (username, password_hash, display_name, role_code, status)
KEY (username)
VALUES ('admin', '120000$jX9qW0w9Lh8AESIzRFVmdw==$Ib5udaU8AP26Z4l1LXiBep1D0kIc0rWjea20RP7ftT8=', '管理员', 'ADMIN', 1);

MERGE INTO sys_user (username, password_hash, display_name, role_code, status)
KEY (username)
VALUES ('alice', '120000$jX9qW0w9Lh8AESIzRFVmdw==$Ib5udaU8AP26Z4l1LXiBep1D0kIc0rWjea20RP7ftT8=', 'Alice', 'USER', 1);

MERGE INTO sys_user (username, password_hash, display_name, role_code, status)
KEY (username)
VALUES ('bob', '120000$jX9qW0w9Lh8AESIzRFVmdw==$Ib5udaU8AP26Z4l1LXiBep1D0kIc0rWjea20RP7ftT8=', 'Bob', 'USER', 0);
