/*
 *  Copyright (C) [2024] smartboot [zhengjunweimail@163.com]
 *
 *  企业用户未经smartboot组织特别许可，需遵循Apache-2.0开源协议合理合法使用本项目。
 *
 *   Enterprise users are required to use this project reasonably
 *   and legally in accordance with the Apache-2.0 open source agreement
 *  without special permission from the smartboot organization.
 */

package tech.smartboot.feat.demo.featclaw.tools;

import com.alibaba.fastjson2.JSONObject;
import tech.smartboot.feat.ai.agent.AgentTool;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.concurrent.CompletableFuture;

/**
 * 代码生成工具 - 为 FeatClaw Agent 提供代码生成能力
 * <p>
 * 该工具允许 AI Agent 根据需求生成代码文件，支持：
 * 1. 生成 Java 类文件（Controller、Service、Entity 等）
 * 2. 生成配置文件（application.properties、logback.xml 等）
 * 3. 生成 Maven pom.xml 片段
 * 4. 生成文档文件（README.md、API 文档等）
 * </p>
 * <p>
 * 为了安全考虑，所有代码生成操作都被限制在指定的工作目录内。
 * </p>
 *
 * @author Feat Team
 * @version v1.0.0
 */
public class CodeGeneratorTool implements AgentTool {

    private static final String NAME = "code_generator";
    private static final String DESCRIPTION = "生成代码文件，支持 Java 类、配置文件、POM 片段等。可用于生成 Controller、Service、Entity、配置文件等。";

    /**
     * 工作目录，限制代码生成在此目录内进行
     */
    private final String workingDirectory;

    /**
     * 默认构造函数
     */
    public CodeGeneratorTool() {
        this.workingDirectory = System.getProperty("user.dir");
    }

    /**
     * 带工作目录参数的构造函数
     *
     * @param workingDirectory 指定的工作目录路径
     */
    public CodeGeneratorTool(String workingDirectory) {
        this.workingDirectory = workingDirectory;
    }

    @Override
    public CompletableFuture<String> execute(JSONObject parameters) {
        String action = parameters.getString("action");

        if (action == null) {
            return CompletableFuture.completedFuture("错误：必须提供 'action' 参数");
        }

        try {
            switch (action) {
                case "generate_java_class":
                    return CompletableFuture.completedFuture(generateJavaClass(parameters));
                case "generate_config":
                    return CompletableFuture.completedFuture(generateConfig(parameters));
                case "generate_pom_snippet":
                    return CompletableFuture.completedFuture(generatePomSnippet(parameters));
                case "generate_document":
                    return CompletableFuture.completedFuture(generateDocument(parameters));
                default:
                    return CompletableFuture.completedFuture("错误：不支持的操作 '" + action + "'");
            }
        } catch (Exception e) {
            return CompletableFuture.completedFuture("执行操作时出错: " + e.getMessage());
        }
    }

    /**
     * 生成 Java 类文件
     */
    private String generateJavaClass(JSONObject parameters) throws IOException {
        String className = parameters.getString("class_name");
        String packageName = parameters.getString("package_name");
        String classType = parameters.getString("class_type"); // controller, service, entity, etc.
        String content = parameters.getString("content");
        String filePath = parameters.getString("file_path");

        if (className == null || content == null) {
            return "错误：生成 Java 类需要提供 class_name 和 content 参数";
        }

        // 构建完整的文件路径
        Path targetPath;
        if (filePath != null) {
            targetPath = Paths.get(workingDirectory, filePath);
        } else if (packageName != null) {
            String packagePath = packageName.replace(".", "/");
            targetPath = Paths.get(workingDirectory, "src/main/java", packagePath, className + ".java");
        } else {
            targetPath = Paths.get(workingDirectory, className + ".java");
        }

        // 确保目录存在
        Files.createDirectories(targetPath.getParent());

        // 构建完整的类内容
        StringBuilder fullContent = new StringBuilder();
        fullContent.append("/*\n");
        fullContent.append(" * Copyright (C) [2024] smartboot\n");
        fullContent.append(" *\n");
        fullContent.append(" * Generated by FeatClaw\n");
        fullContent.append(" */\n\n");
        
        if (packageName != null) {
            fullContent.append("package ").append(packageName).append(";\n\n");
        }
        
        fullContent.append(content);

        // 写入文件
        Files.write(targetPath, fullContent.toString().getBytes(StandardCharsets.UTF_8));

        return String.format("成功生成 Java 类文件: %s\n类型: %s\n路径: %s",
            className, classType != null ? classType : "unknown", targetPath);
    }

    /**
     * 生成配置文件
     */
    private String generateConfig(JSONObject parameters) throws IOException {
        String configType = parameters.getString("config_type"); // properties, yaml, xml
        String fileName = parameters.getString("file_name");
        String content = parameters.getString("content");
        String directory = parameters.getString("directory");

        if (fileName == null || content == null) {
            return "错误：生成配置文件需要提供 file_name 和 content 参数";
        }

        // 构建目标路径
        Path targetDir = directory != null 
            ? Paths.get(workingDirectory, directory)
            : Paths.get(workingDirectory, "src/main/resources");
        Path targetPath = targetDir.resolve(fileName);

        // 确保目录存在
        Files.createDirectories(targetDir);

        // 写入文件
        Files.write(targetPath, content.getBytes(StandardCharsets.UTF_8));

        return String.format("成功生成配置文件: %s\n类型: %s\n路径: %s",
            fileName, configType != null ? configType : "unknown", targetPath);
    }

    /**
     * 生成 POM.xml 片段
     */
    private String generatePomSnippet(JSONObject parameters) {
        String snippetType = parameters.getString("snippet_type"); // dependency, plugin, profile
        String content = parameters.getString("content");

        if (content == null) {
            return "错误：生成 POM 片段需要提供 content 参数";
        }

        // POM 片段只是返回内容，实际合并需要人工处理
        return String.format("POM %s 片段已生成:\n%s", 
            snippetType != null ? snippetType : "dependency", content);
    }

    /**
     * 生成文档文件
     */
    private String generateDocument(JSONObject parameters) throws IOException {
        String docType = parameters.getString("doc_type"); // markdown, ascii, html
        String fileName = parameters.getString("file_name");
        String content = parameters.getString("content");
        String directory = parameters.getString("directory");

        if (fileName == null || content == null) {
            return "错误：生成文档需要提供 file_name 和 content 参数";
        }

        // 构建目标路径
        Path targetDir = directory != null 
            ? Paths.get(workingDirectory, directory)
            : Paths.get(workingDirectory);
        Path targetPath = targetDir.resolve(fileName);

        // 确保目录存在
        Files.createDirectories(targetDir);

        // 写入文件
        Files.write(targetPath, content.getBytes(StandardCharsets.UTF_8));

        return String.format("成功生成文档: %s\n类型: %s\n路径: %s",
            fileName, docType != null ? docType : "unknown", targetPath);
    }

    @Override
    public String getName() {
        return NAME;
    }

    @Override
    public String getDescription() {
        return DESCRIPTION;
    }

    @Override
    public String getParametersSchema() {
        return "{\n" +
            "  \"type\": \"object\",\n" +
            "  \"properties\": {\n" +
            "    \"action\": {\n" +
            "      \"type\": \"string\",\n" +
            "      \"enum\": [\"generate_java_class\", \"generate_config\", \"generate_pom_snippet\", \"generate_document\"],\n" +
            "      \"description\": \"要执行的代码生成操作类型\"\n" +
            "    },\n" +
            "    \"class_name\": {\n" +
            "      \"type\": \"string\",\n" +
            "      \"description\": \"类名（用于 generate_java_class）\"\n" +
            "    },\n" +
            "    \"package_name\": {\n" +
            "      \"type\": \"string\",\n" +
            "      \"description\": \"包名（用于 generate_java_class）\"\n" +
            "    },\n" +
            "    \"class_type\": {\n" +
            "      \"type\": \"string\",\n" +
            "      \"enum\": [\"controller\", \"service\", \"entity\", \"repository\", \"config\", \"util\"],\n" +
            "      \"description\": \"类类型（用于 generate_java_class）\"\n" +
            "    },\n" +
            "    \"file_name\": {\n" +
            "      \"type\": \"string\",\n" +
            "      \"description\": \"文件名\"\n" +
            "    },\n" +
            "    \"file_path\": {\n" +
            "      \"type\": \"string\",\n" +
            "      \"description\": \"文件路径（相对路径）\"\n" +
            "    },\n" +
            "    \"config_type\": {\n" +
            "      \"type\": \"string\",\n" +
            "      \"enum\": [\"properties\", \"yaml\", \"xml\", \"json\"],\n" +
            "      \"description\": \"配置文件类型\"\n" +
            "    },\n" +
            "    \"doc_type\": {\n" +
            "      \"type\": \"string\",\n" +
            "      \"enum\": [\"markdown\", \"ascii\", \"html\"],\n" +
            "      \"description\": \"文档类型\"\n" +
            "    },\n" +
            "    \"snippet_type\": {\n" +
            "      \"type\": \"string\",\n" +
            "      \"enum\": [\"dependency\", \"plugin\", \"profile\"],\n" +
            "      \"description\": \"POM 片段类型\"\n" +
            "    },\n" +
            "    \"content\": {\n" +
            "      \"type\": \"string\",\n" +
            "      \"description\": \"文件内容\"\n" +
            "    },\n" +
            "    \"directory\": {\n" +
            "      \"type\": \"string\",\n" +
            "      \"description\": \"目标目录（相对路径）\"\n" +
            "    }\n" +
            "  },\n" +
            "  \"required\": [\"action\"]\n" +
            "}";
    }
}
